export const TEST_ORDER_RB = {
	idOrder: 17679,
	counterparty: "ГРОДНЕНСКИЙ МЯСОКОМБИНАТ",
	contact: "",
	cargo: 'Голяшка "КРЕСТЬЯНСКАЯ"(к/в,фас)Гродно1кг, ',
	typeLoad: "Задняя",
	methodLoad: "На паллетах",
	typeTruck: "Тент",
	temperature: "",
	control: false,
	comment: "",
	status: 20,
	dateCreate: 1724187600000,
	dateDelivery: 1723755600000,
	manager: "Тестовый Сотрудник Закупок; GoncharukI@dobronom.by",
	telephoneManager: "+375",
	stacking: false,
	logist: null,
	logistTelephone: null,
	marketNumber: "19480245",
	onloadWindowDate: null,
	onloadWindowTime: null,
	loadNumber: "19480245",
	numStockDelivery: "1200",
	pall: "6",
	addresses: [
		{
			idAddress: 11361,
			bodyAddress: "BY Беларусь; Склад 1200, 223039, Минская обл., Минский р-н, Хатежинский с/с, 1",
			date: 1724360400000,
			type: "Выгрузка",
			pall: "6",
			weight: "444",
			volume: null,
			comment: null,
			timeFrame: "С 12:03 по 12:03",
			contact: "qweqwe, тел. 123123",
			cargo: 'Голяшка "КРЕСТЬЯНСКАЯ"(к/в,фас)Гродно1кг, ',
			customsAddress: null,
			time: null,
			isCorrect: true,
			oldIdaddress: null,
			tnvd: null,
			pointNumber: 2,
		},
		{
			idAddress: 11360,
			bodyAddress: "BY Беларусь; qweqwe",
			date: 1724360400000,
			type: "Загрузка",
			pall: "6",
			weight: "444",
			volume: null,
			comment: null,
			timeFrame: "С 12:03 по 12:03",
			contact: "qweqwe, тел. 123123",
			cargo: 'Голяшка "КРЕСТЬЯНСКАЯ"(к/в,фас)Гродно1кг, ',
			customsAddress: null,
			time: "08:00:00",
			isCorrect: true,
			oldIdaddress: null,
			tnvd: "",
			pointNumber: 1,
		},
	],
	routes: [],
	way: "РБ",
	onloadTime: null,
	incoterms: "",
	changeStatus: "Создал: Гончарук Илья Игоревич 27.08.2024 12:19:51",
	needUnloadPoint: null,
	idRamp: 120003,
	timeDelivery: 1724920800000,
	timeUnload: "00:27:00",
	loginManager: "procur%!test",
	sku: 2,
	monoPall: 4,
	mixPall: 2,
	isInternalMovement: "false",
	mailInfo: null,
	slotInfo: null,
	dateCreateMarket: 1723582800000,
	marketInfo: null,
	marketContractType: null,
	marketContractGroupId: null,
	marketContractNumber: null,
	marketContractorId: "22563",
	numProduct: "435076^448789^",
	statusYard: null,
	unloadStartYard: null,
	unloadFinishYard: null,
	pallFactYard: null,
	weightFactYard: null,
	marketOrderSumFirst: null,
	marketOrderSumFinal: null,
	arrivalFactYard: null,
	registrationFactYard: null,
	addressesSort: null,
	addressesToView: [
		{
			idAddress: 11360,
			bodyAddress: "BY Беларусь; qweqwe",
			date: 1724360400000,
			type: "Загрузка",
			pall: "6",
			weight: "444",
			volume: null,
			comment: null,
			timeFrame: "С 12:03 по 12:03",
			contact: "qweqwe, тел. 123123",
			cargo: 'Голяшка "КРЕСТЬЯНСКАЯ"(к/в,фас)Гродно1кг, ',
			customsAddress: null,
			time: "08:00:00",
			isCorrect: true,
			oldIdaddress: null,
			tnvd: "",
			pointNumber: 1,
			dateToView: "23.08.2024",
			info: 'Груз: Голяшка "КРЕСТЬЯНСКАЯ"(к/в,фас)Гродно1кг, ; Паллеты: 6 шт; Масса: 444 кг; ',
		},
		{
			idAddress: 11361,
			bodyAddress: "BY Беларусь; Склад 1200, 223039, Минская обл., Минский р-н, Хатежинский с/с, 1",
			date: 1724360400000,
			type: "Выгрузка",
			pall: "6",
			weight: "444",
			volume: null,
			comment: null,
			timeFrame: "С 12:03 по 12:03",
			contact: "qweqwe, тел. 123123",
			cargo: 'Голяшка "КРЕСТЬЯНСКАЯ"(к/в,фас)Гродно1кг, ',
			customsAddress: null,
			time: null,
			isCorrect: true,
			oldIdaddress: null,
			tnvd: null,
			pointNumber: 2,
			dateToView: "23.08.2024",
			info: 'Груз: Голяшка "КРЕСТЬЯНСКАЯ"(к/в,фас)Гродно1кг, ; Паллеты: 6 шт; Масса: 444 кг; ',
		},
	],
	dateCreateToView: "21.08.2024",
	dateDeliveryToView: "16.08.2024",
	controlToView: "Нет",
	loadDateToView: "23.08.2024",
	unloadDateToView: "23.08.2024",
	managerToView: "Тестовый Сотрудник Закупок; GoncharukI@dobronom.by; тел. +375",
	statusToView: "В обработке у логистов",
	stackingToView: "Нет",
	logistToView: "",
	unloadWindowToView: "",
	loadPoints: "1) BY Беларусь; qweqwe",
	unloadPoints: "1) BY Беларусь; Склад 1200, 223039, Минская обл., Минский р-н, Хатежинский с/с, 1",
	summPall: 6,
	summVolume: null,
	summWeight: 444,
	routeInfo: "",
	routePrice: "",
	wayToView: "РБ",
};
export const TEST_ORDER_IMPORT = {
	idOrder: 17681,
	counterparty: "ФИЛИАЛ №1 НЕСТ ИООО АЛИДИ-ВЕСТ",
	contact: "",
	cargo: 'Корм "FELIX" (лосось, желе) 75г, ',
	typeLoad: "Боковая",
	methodLoad: "Навалом",
	typeTruck: "Контейнер 20 футов",
	temperature: "",
	control: true,
	comment: "test comment",
	status: 20,
	dateCreate: 1724792400000,
	dateDelivery: 1723755600000,
	manager: "Гончарук Илья Игоревич; GoncharukI@dobronom.by",
	telephoneManager: "+375",
	stacking: false,
	logist: null,
	logistTelephone: null,
	marketNumber: "19480246",
	onloadWindowDate: null,
	onloadWindowTime: null,
	loadNumber: "19480246",
	numStockDelivery: "1700",
	pall: "9",
	addresses: [
		{
			idAddress: 11369,
			bodyAddress:
				"BY Беларусь; Склад 1700, 223065, Минская обл., Минский р-н, Луговослободской с/с, РАД М4, 18км. 2а, склад W05",
			date: 1725397200000,
			type: "Выгрузка",
			pall: "9",
			weight: "800",
			volume: null,
			comment: null,
			timeFrame: "Будние дни: с 00:00 по 23:59; Суббота: с 00:00 по 23:59; Воскресенье: с 00:00 по 23:59",
			contact: "Раблотник склада, тел. 123123",
			cargo: 'Корм "FELIX" (лосось, желе) 75г, ',
			customsAddress: "BY Беларусь; 333333, Минская, Луговослободской с/с, РАД М4 18км склад W05, 2а",
			time: "19:00:00",
			isCorrect: true,
			oldIdaddress: null,
			tnvd: null,
			pointNumber: 2,
		},
		{
			idAddress: 11368,
			bodyAddress: "BE Бельгия; 123456, ыываываы, пролд, смистьибитб, 2",
			date: 1725051600000,
			type: "Загрузка",
			pall: "9",
			weight: "800",
			volume: null,
			comment: null,
			timeFrame: "Будние дни: с 09:00 по 21:00; Суббота: с 10:00 по 18:00; Воскресенье: не работают",
			contact: "ываыва ываыва, тел. 2342342342",
			cargo: 'Корм "FELIX" (лосось, желе) 75г, ',
			customsAddress: "Затаможка на месте загрузки",
			time: "09:00:00",
			isCorrect: true,
			oldIdaddress: null,
			tnvd: "1231231",
			pointNumber: 1,
		},
	],
	routes: [],
	way: "Импорт",
	onloadTime: null,
	incoterms: "FAS – Free Alongside Ship",
	changeStatus: "Создал: Тестовый Сотрудник Закупок 28.08.2024 10:59:43",
	needUnloadPoint: null,
	idRamp: 170002,
	timeDelivery: 1725438000000,
	timeUnload: "00:35:00",
	loginManager: "procur%!test",
	sku: 3,
	monoPall: 8,
	mixPall: 1,
	isInternalMovement: "false",
	mailInfo: null,
	slotInfo: null,
	dateCreateMarket: 1723582800000,
	marketInfo: null,
	marketContractType: null,
	marketContractGroupId: null,
	marketContractNumber: null,
	marketContractorId: "114108",
	numProduct: "1475134^1475132^674861^",
	statusYard: null,
	unloadStartYard: null,
	unloadFinishYard: null,
	pallFactYard: null,
	weightFactYard: null,
	marketOrderSumFirst: null,
	marketOrderSumFinal: null,
	arrivalFactYard: null,
	registrationFactYard: null,
	addressesSort: null,
	addressesToView: [
		{
			idAddress: 11368,
			bodyAddress: "BE Бельгия; 123456, ыываываы, пролд, смистьибитб, 2",
			date: 1725051600000,
			type: "Загрузка",
			pall: "9",
			weight: "800",
			volume: null,
			comment: null,
			timeFrame: "Будние дни: с 09:00 по 21:00; Суббота: с 10:00 по 18:00; Воскресенье: не работают",
			contact: "ываыва ываыва, тел. 2342342342",
			cargo: 'Корм "FELIX" (лосось, желе) 75г, ',
			customsAddress: "Затаможка на месте загрузки",
			time: "09:00:00",
			isCorrect: true,
			oldIdaddress: null,
			tnvd: "1231231",
			pointNumber: 1,
			dateToView: "31.08.2024",
			info: 'Груз: Корм "FELIX" (лосось, желе) 75г, ; Паллеты: 9 шт; Масса: 800 кг; ',
		},
		{
			idAddress: 11369,
			bodyAddress:
				"BY Беларусь; Склад 1700, 223065, Минская обл., Минский р-н, Луговослободской с/с, РАД М4, 18км. 2а, склад W05",
			date: 1725397200000,
			type: "Выгрузка",
			pall: "9",
			weight: "800",
			volume: null,
			comment: null,
			timeFrame: "Будние дни: с 00:00 по 23:59; Суббота: с 00:00 по 23:59; Воскресенье: с 00:00 по 23:59",
			contact: "Раблотник склада, тел. 123123",
			cargo: 'Корм "FELIX" (лосось, желе) 75г, ',
			customsAddress: "BY Беларусь; 333333, Минская, Луговослободской с/с, РАД М4 18км склад W05, 2а",
			time: "19:00:00",
			isCorrect: true,
			oldIdaddress: null,
			tnvd: null,
			pointNumber: 2,
			dateToView: "04.09.2024",
			info: 'Груз: Корм "FELIX" (лосось, желе) 75г, ; Паллеты: 9 шт; Масса: 800 кг; ',
		},
	],
	dateCreateToView: "28.08.2024",
	dateDeliveryToView: "16.08.2024",
	controlToView: "Да",
	loadDateToView: "31.08.2024",
	unloadDateToView: "04.09.2024",
	managerToView: "Гончарук Илья Игоревич; GoncharukI@dobronom.by; тел. +375",
	statusToView: "В обработке у логистов",
	stackingToView: "Нет",
	logistToView: "",
	unloadWindowToView: "",
	loadPoints: "1) BE Бельгия; 123456, ыываываы, пролд, смистьибитб, 2",
	unloadPoints:
		"1) BY Беларусь; Склад 1700, 223065, Минская обл., Минский р-н, Луговослободской с/с, РАД М4, 18км. 2а, склад W05",
	summPall: 9,
	summVolume: null,
	summWeight: 800,
	routeInfo: "",
	routePrice: "",
	wayToView: "Импорт",
};
export const TEST_ORDER_EXPORT = {
	"idOrder": 17683,
	"counterparty": "Export 4",
	"contact": "",
	"cargo": "qweq",
	"typeLoad": "Боковая",
	"methodLoad": "На паллетах",
	"typeTruck": "Тент",
	"temperature": "",
	"control": false,
	"comment": "",
	"status": 20,
	"dateCreate": 1724706000000,
	"dateDelivery": 1725051600000,
	"manager": "Гончарук Илья Игоревич; GoncharukI@dobronom.by",
	"telephoneManager": "+375",
	"stacking": false,
	"logist": null,
	"logistTelephone": null,
	"marketNumber": "",
	"onloadWindowDate": null,
	"onloadWindowTime": null,
	"loadNumber": "12312",
	"numStockDelivery": null,
	"pall": "33",
	"addresses": [
		{
			"idAddress": 11366,
			"bodyAddress": "BY Беларусь; qweqweq",
			"date": 1724965200000,
			"type": "Загрузка",
			"pall": "33",
			"weight": "333",
			"volume": null,
			"comment": null,
			"timeFrame": "С 12:12 по 12:12",
			"contact": "qweqwe, тел. 12312",
			"cargo": "qweqwwe",
			"customsAddress": null,
			"time": "09:00:00",
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": "12312",
			"pointNumber": 1
		},
		{
			"idAddress": 11367,
			"bodyAddress": "qweqwe; 1qweqwe",
			"date": 1725051600000,
			"type": "Выгрузка",
			"pall": "33",
			"weight": "333",
			"volume": null,
			"comment": null,
			"timeFrame": "С 12:03 по 12:31",
			"contact": "qweqwe, тел. 123123",
			"cargo": "qweqwwe",
			"customsAddress": null,
			"time": null,
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": null,
			"pointNumber": 2
		}
	],
	"routes": [],
	"way": "Экспорт",
	"onloadTime": null,
	"incoterms": "",
	"changeStatus": "Создал: Гончарук Илья Игоревич 27.08.2024 12:36:25",
	"needUnloadPoint": null,
	"idRamp": null,
	"timeDelivery": null,
	"timeUnload": null,
	"loginManager": null,
	"sku": null,
	"monoPall": null,
	"mixPall": null,
	"isInternalMovement": "false",
	"mailInfo": null,
	"slotInfo": null,
	"dateCreateMarket": null,
	"marketInfo": null,
	"marketContractType": null,
	"marketContractGroupId": null,
	"marketContractNumber": null,
	"marketContractorId": null,
	"numProduct": null,
	"statusYard": null,
	"unloadStartYard": null,
	"unloadFinishYard": null,
	"pallFactYard": null,
	"weightFactYard": null,
	"marketOrderSumFirst": null,
	"marketOrderSumFinal": null,
	"arrivalFactYard": null,
	"registrationFactYard": null,
	"addressesSort": null,
	"addressesToView": [
		{
			"idAddress": 11366,
			"bodyAddress": "BY Беларусь; qweqweq",
			"date": 1724965200000,
			"type": "Загрузка",
			"pall": "33",
			"weight": "333",
			"volume": null,
			"comment": null,
			"timeFrame": "С 12:12 по 12:12",
			"contact": "qweqwe, тел. 12312",
			"cargo": "qweqwwe",
			"customsAddress": null,
			"time": "09:00:00",
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": "12312",
			"pointNumber": 1,
			"dateToView": "30.08.2024",
			"info": "Груз: qweqwwe; Паллеты: 33 шт; Масса: 333 кг; "
		},
		{
			"idAddress": 11367,
			"bodyAddress": "qweqwe; 1qweqwe",
			"date": 1725051600000,
			"type": "Выгрузка",
			"pall": "33",
			"weight": "333",
			"volume": null,
			"comment": null,
			"timeFrame": "С 12:03 по 12:31",
			"contact": "qweqwe, тел. 123123",
			"cargo": "qweqwwe",
			"customsAddress": null,
			"time": null,
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": null,
			"pointNumber": 2,
			"dateToView": "31.08.2024",
			"info": "Груз: qweqwwe; Паллеты: 33 шт; Масса: 333 кг; "
		}
	],
	"dateCreateToView": "27.08.2024",
	"dateDeliveryToView": "31.08.2024",
	"controlToView": "Нет",
	"loadDateToView": "30.08.2024",
	"unloadDateToView": "31.08.2024",
	"managerToView": "Гончарук Илья Игоревич; GoncharukI@dobronom.by; тел. +375",
	"statusToView": "В обработке у логистов",
	"stackingToView": "Нет",
	"logistToView": "",
	"unloadWindowToView": "",
	"loadPoints": "1) BY Беларусь; qweqweq",
	"unloadPoints": "1) qweqwe; 1qweqwe",
	"summPall": 33,
	"summVolume": null,
	"summWeight": 333,
	"routeInfo": "",
	"routePrice": "",
	"wayToView": "Экспорт"
}
export const TEST_ORDER_IM = {
	"idOrder": 17674,
	"counterparty": "ЗАО \"Доброном\"",
	"contact": "",
	"cargo": "qweq",
	"typeLoad": "Задняя",
	"methodLoad": "На паллетах",
	"typeTruck": "Тент",
	"temperature": "",
	"control": false,
	"comment": "",
	"status": 30,
	"dateCreate": 1724187600000,
	"dateDelivery": 1724274000000,
	"manager": "Гончарук Илья Игоревич; GoncharukI@dobronom.by",
	"telephoneManager": "+375",
	"stacking": false,
	"logist": "Гончарук Илья Игоревич; ",
	"logistTelephone": "+375",
	"marketNumber": "1724229479878",
	"onloadWindowDate": null,
	"onloadWindowTime": null,
	"loadNumber": "12312",
	"numStockDelivery": "1200",
	"pall": "3",
	"addresses": [
		{
			"idAddress": 11348,
			"bodyAddress": "BY Беларусь; 71-Склад Минская обл, Минский р-н, Ждановичский с/с,51,р-н д.Дегтяревка",
			"date": 1724274000000,
			"type": "Загрузка",
			"pall": "3",
			"weight": "333",
			"volume": "4",
			"comment": null,
			"timeFrame": "С 21:31 по 12:03",
			"contact": "qweqwe, тел. 123123",
			"cargo": "qweqe",
			"customsAddress": null,
			"time": "08:00:00",
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": "",
			"pointNumber": null
		},
		{
			"idAddress": 11349,
			"bodyAddress": "BY Беларусь; 1200-Склад 223039, Республика Беларусь, Минская область, Минский район, Хатежинский с/с, 1",
			"date": 1724274000000,
			"type": "Выгрузка",
			"pall": "3",
			"weight": "333",
			"volume": "4",
			"comment": null,
			"timeFrame": "С 11:39 по 12:03",
			"contact": "qweqweq123, тел. 123123",
			"cargo": "qweqe",
			"customsAddress": null,
			"time": null,
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": null,
			"pointNumber": null
		}
	],
	"routes": [
		{
			"idRoute": 20898,
			"numStock": null,
			"dateLoadPreviously": "2024-08-22",
			"timeLoadPreviously": "08:00",
			"timeLoadPreviouslyStock": null,
			"actualTimeArrival": null,
			"startLoad": null,
			"finishLoad": null,
			"deliveryDocuments": null,
			"isSanitization": false,
			"temperature": "",
			"nameLoader": null,
			"ramp": null,
			"totalLoadPall": "3",
			"totalCargoWeight": "333",
			"lines": null,
			"comments": "international",
			"routeDirection": "<ЗАО \"Доброном\"> 71-Склад Минская обл, Минский р-н, Ждановичский с/с,51,р-н д.Дегтяревка - 1200-Склад 223039, Республика Беларусь, Минская область, Минский район, Хатежинский с/с, 1 N20898",
			"startPrice": null,
			"finishPrice": null,
			"time": "00-05",
			"statusRoute": "0",
			"statusStock": "0",
			"typeTrailer": "Тент",
			"startCurrency": null,
			"userComments": "\nЗагрузка 1 - Время работы: С 21:31 по 12:03\nЗагрузка 1 - Контакт : qweqwe, тел. 123123\nВыгрузка 2 - Время работы: С 11:39 по 12:03\nВыгрузка 2 - Контакт : qweqweq123, тел. 123123",
			"stepCost": null,
			"optimalCost": "1000",
			"customer": "Гончарук Илья Игоревич; GoncharukI@dobronom.by",
			"run": null,
			"logistInfo": "Гончарук Илья Игоревич; +375",
			"tnvd": "",
			"way": "РБ",
			"expeditionCost": null,
			"loadNumber": "12312",
			"dateLoadActually": null,
			"timeLoadActually": null,
			"dateUnloadActually": null,
			"timeUnloadActually": null,
			"truck": null,
			"roteHasShop": [
				{
					"idRouteHasShop": 42248,
					"order": 1,
					"pall": "3",
					"weight": "333",
					"status": null,
					"address": "BY Беларусь; 71-Склад Минская обл, Минский р-н, Ждановичский с/с,51,р-н д.Дегтяревка",
					"cargo": "qweqe",
					"position": "Загрузка",
					"volume": "4",
					"customsAddress": null
				},
				{
					"idRouteHasShop": 42249,
					"order": 2,
					"pall": "3",
					"weight": "333",
					"status": null,
					"address": "BY Беларусь; 1200-Склад 223039, Республика Беларусь, Минская область, Минский район, Хатежинский с/с, 1",
					"cargo": "qweqe",
					"position": "Выгрузка",
					"volume": "4",
					"customsAddress": null
				}
			],
			"driver": null,
			"timeUnloadPreviouslyStock": "10:00:00",
			"dateUnloadPreviouslyStock": "2024-08-24",
			"createDate": 1724619600000,
			"createTime": "16:06:15",
			"onloadWindowDate": null,
			"onloadWindowTime": null,
			"onloadTime": null,
			"cost": {},
			"nds": null,
			"numWayList": null,
			"numTruckAndTrailer": null,
			"cmr": null,
			"costWay": null,
			"dateUnload": null,
			"cargoWeightForAct": null,
			"simpleRoute": {
				"idRoute": 20898,
				"dateLoadPreviously": "22-08-2024",
				"routeDirection": "<ЗАО \"Доброном\"> 71-Склад Минская обл, Минский р-н, Ждановичский с/с,51,р-н д.Дегтяревка - 1200-Склад 223039, Республика Беларусь, Минская область, Минский район, Хатежинский с/с, 1 N20898",
				"finishPrice": null,
				"startCurrency": null
			},
			"numPoint": "2",
			"simpleWay": "РБ",
			"simpleDateStart": "22-08-2024",
			"sanitization": false,
			"simpleDateActually": null,
			"dateUnloadActuallySimple": null,
			"dateLoadActuallySimple": null
		}
	],
	"way": "РБ",
	"onloadTime": null,
	"incoterms": "",
	"changeStatus": "Создал: Тестовый Сотрудник Закупок 21.08.2024 12:18:11\nМаршрут создал: ГончарукИльяИгоревич 26.08.2024 16:06:48",
	"needUnloadPoint": null,
	"idRamp": 120001,
	"timeDelivery": 1724482800000,
	"timeUnload": "01:00:00",
	"loginManager": "procur%!test",
	"sku": null,
	"monoPall": null,
	"mixPall": null,
	"isInternalMovement": "true",
	"mailInfo": null,
	"slotInfo": null,
	"dateCreateMarket": null,
	"marketInfo": null,
	"marketContractType": null,
	"marketContractGroupId": null,
	"marketContractNumber": null,
	"marketContractorId": null,
	"numProduct": null,
	"statusYard": null,
	"unloadStartYard": null,
	"unloadFinishYard": null,
	"pallFactYard": null,
	"weightFactYard": null,
	"marketOrderSumFirst": null,
	"marketOrderSumFinal": null,
	"arrivalFactYard": null,
	"registrationFactYard": null,
	"addressesSort": null,
	"addressesToView": [
		{
			"idAddress": 11348,
			"bodyAddress": "BY Беларусь; 71-Склад Минская обл, Минский р-н, Ждановичский с/с,51,р-н д.Дегтяревка",
			"date": 1724274000000,
			"type": "Загрузка",
			"pall": "3",
			"weight": "333",
			"volume": "4",
			"comment": null,
			"timeFrame": "С 21:31 по 12:03",
			"contact": "qweqwe, тел. 123123",
			"cargo": "qweqe",
			"customsAddress": null,
			"time": "08:00:00",
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": "",
			"pointNumber": 1,
			"dateToView": "22.08.2024",
			"info": "Груз: qweqe; Паллеты: 3 шт; Масса: 333 кг; Объем: 4 м.куб. "
		},
		{
			"idAddress": 11349,
			"bodyAddress": "BY Беларусь; 1200-Склад 223039, Республика Беларусь, Минская область, Минский район, Хатежинский с/с, 1",
			"date": 1724274000000,
			"type": "Выгрузка",
			"pall": "3",
			"weight": "333",
			"volume": "4",
			"comment": null,
			"timeFrame": "С 11:39 по 12:03",
			"contact": "qweqweq123, тел. 123123",
			"cargo": "qweqe",
			"customsAddress": null,
			"time": null,
			"isCorrect": true,
			"oldIdaddress": null,
			"tnvd": null,
			"pointNumber": 2,
			"dateToView": "22.08.2024",
			"info": "Груз: qweqe; Паллеты: 3 шт; Масса: 333 кг; Объем: 4 м.куб. "
		}
	],
	"dateCreateToView": "21.08.2024",
	"dateDeliveryToView": "22.08.2024",
	"controlToView": "Нет",
	"loadDateToView": "22.08.2024",
	"unloadDateToView": "22.08.2024",
	"managerToView": "Гончарук Илья Игоревич; GoncharukI@dobronom.by; тел. +375",
	"statusToView": "Маршрут создан, но не на бирже",
	"stackingToView": "Нет",
	"logistToView": "Гончарук Илья Игоревич; , тел. +375",
	"unloadWindowToView": "",
	"loadPoints": "1) BY Беларусь; 71-Склад Минская обл, Минский р-н, Ждановичский с/с,51,р-н д.Дегтяревка",
	"unloadPoints": "1) BY Беларусь; 1200-Склад 223039, Республика Беларусь, Минская область, Минский район, Хатежинский с/с, 1",
	"summPall": 3,
	"summVolume": 4,
	"summWeight": 333,
	"routeInfo": "1) Маршрут <ЗАО \"Доброном\"> 71-Склад Минская обл, Минский р-н, Ждановичский с/с,51,р-н д.Дегтяревка - 1200-Склад 223039, Республика Беларусь, Минская область, Минский район, Хатежинский с/с, 1 N20898",
	"routePrice": "",
	"wayToView": "Внутреннее перемещение"
}
