export const shiftLoads = [
	{
		"idshift_load" : 1,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1414,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 2,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 27545,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 3,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6776,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 4,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 97316,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 5,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 110931,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 6,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 157158,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 7,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 137018,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 8,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 7809,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 9,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 113571,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 10,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 149890,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 11,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 24986,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 12,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 120055,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 13,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 97503,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 14,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 92535,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 15,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 129736,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 16,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 24643,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 17,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 5907,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 18,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 96540,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 19,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 88839,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 20,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 142525,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 21,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 22563,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 22,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 106160,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 23,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 2,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 24,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 110793,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 25,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 99409,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 26,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 105611,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 27,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 114698,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 28,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1789,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 29,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 9732,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 30,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8683,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 31,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 22054,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 32,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 114283,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 33,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 143708,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 34,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 134641,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 35,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 27943,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 36,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 105715,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 37,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 44351,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 38,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6014,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 39,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90956,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 40,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8875,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 41,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 145678,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 42,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 155335,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 43,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 159949,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 44,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 147292,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 45,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 99681,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 46,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 161929,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 47,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 131132,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 48,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 157028,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 49,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 99314,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 50,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 27395,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 51,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 2277,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 52,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 107069,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 53,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 11523,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 54,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 14171,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 55,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 35056,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 56,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 156982,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 57,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 143792,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 58,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8334,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 59,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 5228,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 60,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 136021,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 61,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 207,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 62,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8706,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 63,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 125533,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 64,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 107081,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 65,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 106812,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 66,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 113870,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 67,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 89185,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 68,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 9674,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 69,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 108606,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 70,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 24985,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 71,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 121416,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 72,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 80076,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 73,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 110335,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 74,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6516,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 75,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 51250,
		"num_stock" : 1200
	},
	{
		"idshift_load" : 76,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 159540,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 77,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 160825,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 78,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 12463,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 79,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1397,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 80,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 106386,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 81,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 144185,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 82,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 141396,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 83,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 163964,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 84,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1414,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 85,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 114128,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 86,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6776,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 87,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 99911,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 88,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 153380,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 89,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 94648,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 90,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 121416,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 91,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 142449,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 92,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 130662,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 93,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 121442,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 94,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 151079,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 95,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 98198,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 96,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 151742,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 97,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 141354,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 98,
		"week" : null,
		"monday" : 1,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6014,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 99,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 124017,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 100,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 156127,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 101,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 105372,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 102,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 149440,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 103,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 101011,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 104,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 88878,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 105,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 118710,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 106,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 54789,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 107,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 91429,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 108,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 1029,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 109,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 110549,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 110,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 115331,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 111,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 93469,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 112,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1087,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 113,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 4492,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 114,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90958,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 115,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 114073,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 116,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 27943,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 117,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 7624,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 118,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 95803,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 119,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 137153,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 120,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 87593,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 121,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 92502,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 122,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 131093,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 123,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 145820,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 124,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 11036,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 125,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 89817,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 126,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8508,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 127,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 94950,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 128,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 99848,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 129,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 132564,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 130,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 160337,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 131,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96133,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 132,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 129736,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 133,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 24643,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 134,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 88839,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 135,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 93256,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 136,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 147593,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 137,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 5150,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 138,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 93980,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 139,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 92839,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 140,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 160301,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 141,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 11998,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 142,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96006,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 143,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 115465,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 144,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 5471,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 145,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 91927,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 146,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 9674,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 147,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 126786,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 148,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 12407,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 149,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 112864,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 150,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 115016,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 151,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 13380,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 152,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 28650,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 153,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 106553,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 154,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 158241,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 155,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 130416,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 156,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 160226,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 157,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 9732,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 158,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 98897,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 159,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 22468,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 160,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90784,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 161,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 82603,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 162,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 158299,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 163,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 90220,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 164,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 89100,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 165,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 12937,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 166,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 108260,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 167,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 152198,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 168,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 101376,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 169,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 5868,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 170,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 122558,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 171,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6944,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 172,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 99253,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 173,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 2,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 174,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 120897,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 175,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 11953,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 176,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6753,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 177,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8121,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 178,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 16399,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 179,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 10132,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 180,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90670,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 181,
		"week" : null,
		"monday" : 1,
		"tuesday" : 1,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 113847,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 182,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 93686,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 183,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 3761,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 184,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 161463,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 185,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 91066,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 186,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 23937,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 187,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 12016,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 188,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 40172,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 189,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96706,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 190,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 13936,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 191,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 91874,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 192,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 159171,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 193,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 110393,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 194,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90249,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 195,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90787,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 196,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 12031,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 197,
		"week" : null,
		"monday" : 1,
		"tuesday" : 1,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 24736,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 198,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 156475,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 199,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 160097,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 200,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 106225,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 201,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 94917,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 202,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 7278,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 203,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 13066,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 204,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 13102,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 205,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 111034,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 206,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 61971,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 207,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90707,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 208,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 82511,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 209,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 30825,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 210,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 12622,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 211,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 7217,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 212,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 113014,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 213,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 5214,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 214,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 81702,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 215,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8041,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 216,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96617,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 217,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1109,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 218,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 12062,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 219,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96540,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 220,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 96795,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 221,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 22625,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 222,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96507,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 223,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 100996,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 224,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 152467,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 225,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 1622527,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 226,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 138533,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 227,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 99314,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 228,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 144027,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 229,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 147276,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 230,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 130272,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 231,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 157264,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 232,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 143882,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 233,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 154166,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 234,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 98990,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 235,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 158747,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 236,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 29146,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 237,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 156659,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 238,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 163409,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 239,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 120465,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 240,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 121061,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 241,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 151252,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 242,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 10154,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 243,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 114711,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 244,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 137508,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 245,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 144468,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 246,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 155812,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 247,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 144629,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 248,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 97637,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 249,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 142447,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 250,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 163864,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 251,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 142251,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 252,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 101343,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 253,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 160397,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 254,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 131550,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 255,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 158264,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 256,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 122360,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 257,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 148306,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 258,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 150972,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 259,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 145909,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 260,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 143440,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 261,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 120941,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 262,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 97002,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 263,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 4644,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 264,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 65238,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 265,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 118596,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 266,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96941,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 267,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 91844,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 268,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 100118,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 269,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 4541,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 270,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 99409,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 271,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 88369,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 272,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 93042,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 273,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 5726,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 274,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 100613,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 275,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 5835,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 276,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 100117,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 277,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 107776,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 278,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 110335,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 279,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 111162,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 280,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 117549,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 281,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 114108,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 282,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 9822,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 283,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 151236,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 284,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 9428,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 285,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 26036,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 286,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1538,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 287,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 111782,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 288,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 110846,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 289,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 9493,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 290,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 124724,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 291,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 164922,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 292,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 69224,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 293,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 113388,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 294,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 115592,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 295,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 119285,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 296,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 96844,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 297,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 121268,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 298,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 142442,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 299,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 114657,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 300,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 115599,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 301,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 101442,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 302,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 97361,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 303,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 97794,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 304,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 105126,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 305,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 141397,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 306,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 140293,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 307,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 146025,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 308,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 98881,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 309,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 109106,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 310,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 107633,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 311,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 111888,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 312,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 1033,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 313,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 131508,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 314,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 131241,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 315,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 90529,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 316,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 91112,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 317,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 152907,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 318,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 13419,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 319,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 41280,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 320,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 137018,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 321,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 89781,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 322,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 114394,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 323,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 121936,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 324,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 108859,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 325,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 104216,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 326,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 128490,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 327,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 99200,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 328,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 12535,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 329,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 139537,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 330,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 40472,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 331,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 161912,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 332,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8706,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 333,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 5910,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 334,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 96115,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 335,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 58910,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 336,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 125897,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 337,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 22542,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 338,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 13508,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 339,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 4786,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 340,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 6334,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 341,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 144692,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 342,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 121793,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 343,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 117874,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 344,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 48046,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 345,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 152854,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 346,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 110543,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 347,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 109835,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 348,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 35319,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 349,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 3650,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 350,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 146461,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 351,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 2606,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 352,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 141951,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 353,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 154744,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 354,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 113437,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 355,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 107486,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 356,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 1,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 11523,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 357,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 8962,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 358,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 118391,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 359,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 118188,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 360,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 97503,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 361,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 125527,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 362,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 98667,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 363,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 145967,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 364,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 104793,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 365,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 52147,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 366,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 142196,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 367,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 144951,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 368,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 141873,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 369,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 128955,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 370,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 157158,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 371,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 1,
		"comment" : null,
		"status" : null,
		"user_iduser" : 10191,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 372,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 156518,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 373,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 107709,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 374,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 117739,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 375,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 26864,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 376,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 153628,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 377,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 135583,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 378,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 109890,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 379,
		"week" : null,
		"monday" : 0,
		"tuesday" : 1,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 121595,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 380,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 1,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 164719,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 381,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 1,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 90882,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 382,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 1,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 135818,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 383,
		"week" : null,
		"monday" : 0,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 1,
		"sunday" : 0,
		"comment" : null,
		"status" : null,
		"user_iduser" : 101960,
		"num_stock" : 1700
	},
	{
		"idshift_load" : 384,
		"week" : null,
		"monday" : 1,
		"tuesday" : 0,
		"wednesday" : 0,
		"thursday" : 0,
		"friday" : 0,
		"saturday" : 0,
		"sunday" : 0,
		"comment" : "неделя",
		"status" : null,
		"user_iduser" : 120911,
		"num_stock" : 1700
	}
]
